# Importing Numpy

In [104]:
import numpy as np

# Creating Input & Output Arrays

In [105]:
X = np.array(([0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]), dtype=float)
y = np.array(([1], [0], [0], [0], [0], [0], [0], [1]), dtype=float)

# Creating the array to be Predicted

In [106]:
xPredicted = np.array(([0, 0, 1]), dtype=float)
X = X/np.amax(X, axis=0)
xPredicted = xPredicted/np.amax(xPredicted, axis=0)

# Creating the File for Losses

In [107]:
lossFile = open("SumSquaredLossList.csv", "w")

# Creating Neural Network Class

In [108]:
class Neural_Network (object):
    def __init__(self):
        self.inputLayerSize = 3
        self.outputLayerSize = 1
        self.hiddenLayerSize = 4
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)

    def feedForward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.activationSigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        out = self.activationSigmoid(self.z3)
        return out

    def backwardPropagate(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error*self.activationSigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.activationSigmoidPrime(self.z2)
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)
        
    def trainNetwork(self, X, y):
        o = self.feedForward(X)
        self.backwardPropagate(X, y, o)
    
    def activationSigmoid(self, s):
        return 1/(1+np.exp(-s))
    
    def activationSigmoidPrime(self, s):
        return s * (1 - s)
    
    def saveSumSquaredLossList(self,i,error):
        lossFile.write(str(i)+","+str(error.tolist())+'\n')

    def saveWeights(self):
        np.savetxt("weightsLayer1.txt", self.W1, fmt="%s")
        np.savetxt("weightsLayer2.txt", self.W2, fmt="%s")
    
    def predictOutput(self):
        print ("Predicted XOR output data based on trained weights: ")
        print ("Expected (X1-X3): \n" + str(xPredicted))
        print ("Output (Y1): \n" + str(self.feedForward(xPredicted)))

# Training & Printing Output

In [109]:
myNeuralNetwork = Neural_Network()
trainingEpochs = 3000001
for i in range(trainingEpochs):
    if i%100000==0:
        print ("Epoch # " + str(i) + "\n")
        print ("Network Input : \n" + str(X))
        print ("Expected Output of XOR Gate Neural Network: \n" + str(y))
        print ("Actual Output from XOR Gate Neural Network: \n" + str(myNeuralNetwork.feedForward(X)))
        Loss = np.mean(np.square(y - myNeuralNetwork.feedForward(X)))
        myNeuralNetwork.saveSumSquaredLossList(i,Loss)
        print ("Sum Squared Loss: \n" + str(Loss))
        print("\n---------------------------------------------------------------")
        print ("\n")
    myNeuralNetwork.trainNetwork(X, y)
myNeuralNetwork.saveWeights()
myNeuralNetwork.predictOutput()

Epoch # 0

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.83475475]
 [0.89774665]
 [0.76892307]
 [0.87230385]
 [0.76947865]
 [0.83563709]
 [0.70679467]
 [0.81192974]]
Sum Squared Loss: 
0.5013409497523477

---------------------------------------------------------------


Epoch # 100000

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.99703716]
 [0.00213348]
 [0.0033989 ]
 [0.00332085]
 [0.00337089]
 [0.00332139]
 [0.0017007 ]
 [0.99421132]]
Sum Squared Loss: 
1.183830602383764e-05

---------------------------------------------------------------


Epoch # 200000

Network Inpu